# Generated by Django 3.1.2 on 2020-10-24 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('1', 'APARTMENT'), ('2', 'VILLA BOR'), ('3', 'VILLA ASPEN'), ('4', 'DOUBLE ROOM'), ('5', 'DELUXE SUITE'), ('6', 'VILLA ELA')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('size', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('1', 'available'), ('2', 'not available')], max_length=15)),
                ('roomnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('guests', models.IntegerField()),
                ('specials', models.TextField(max_length=256, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(default='null', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
