# Generated by Django 3.1.2 on 2020-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='podvisbor', max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('country', models.CharField(default='Bulgaria', max_length=50)),
            ],
        ),
    ]
