# Generated by Django 3.1.2 on 2020-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20201027_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Vila_Bor ', 'VILLA BOR'), ('Vila Aspen', 'VILLA ASPEN'), ('Vila Ela', 'VILLA ELA')], max_length=50),
        ),
    ]
